/* Decode header for epiphanybf.

THIS FILE IS MACHINE GENERATED WITH CGEN.

Copyright 1996-2010 Free Software Foundation, Inc.

This file is part of the GNU simulators.

   This file is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3, or (at your option)
   any later version.

   It is distributed in the hope that it will be useful, but WITHOUT
   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
   or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
   License for more details.

   You should have received a copy of the GNU General Public License along
   with this program; if not, write to the Free Software Foundation, Inc.,
   51 Franklin Street - Fifth Floor, Boston, MA 02110-1301, USA.

*/

#ifndef EPIPHANYBF_DECODE_H
#define EPIPHANYBF_DECODE_H

extern const IDESC *epiphanybf_decode (SIM_CPU *, IADDR,
                                  CGEN_INSN_WORD, CGEN_INSN_WORD,
                                  ARGBUF *);
extern void epiphanybf_init_idesc_table (SIM_CPU *);
extern void epiphanybf_sem_init_idesc_table (SIM_CPU *);
extern void epiphanybf_semf_init_idesc_table (SIM_CPU *);

/* Enum declaration for instructions in cpu family epiphanybf.  */
typedef enum epiphanybf_insn_type {
  EPIPHANYBF_INSN_X_INVALID, EPIPHANYBF_INSN_X_AFTER, EPIPHANYBF_INSN_X_BEFORE, EPIPHANYBF_INSN_X_CTI_CHAIN
 , EPIPHANYBF_INSN_X_CHAIN, EPIPHANYBF_INSN_X_BEGIN, EPIPHANYBF_INSN_BEQ16, EPIPHANYBF_INSN_BEQ
 , EPIPHANYBF_INSN_BNE16, EPIPHANYBF_INSN_BNE, EPIPHANYBF_INSN_BGTU16, EPIPHANYBF_INSN_BGTU
 , EPIPHANYBF_INSN_BGTEU16, EPIPHANYBF_INSN_BGTEU, EPIPHANYBF_INSN_BLTEU16, EPIPHANYBF_INSN_BLTEU
 , EPIPHANYBF_INSN_BLTU16, EPIPHANYBF_INSN_BLTU, EPIPHANYBF_INSN_BGT16, EPIPHANYBF_INSN_BGT
 , EPIPHANYBF_INSN_BGTE16, EPIPHANYBF_INSN_BGTE, EPIPHANYBF_INSN_BLT16, EPIPHANYBF_INSN_BLT
 , EPIPHANYBF_INSN_BLTE16, EPIPHANYBF_INSN_BLTE, EPIPHANYBF_INSN_BBEQ16, EPIPHANYBF_INSN_BBEQ
 , EPIPHANYBF_INSN_BBNE16, EPIPHANYBF_INSN_BBNE, EPIPHANYBF_INSN_BBLT16, EPIPHANYBF_INSN_BBLT
 , EPIPHANYBF_INSN_BBLTE16, EPIPHANYBF_INSN_BBLTE, EPIPHANYBF_INSN_B16, EPIPHANYBF_INSN_B
 , EPIPHANYBF_INSN_BL16, EPIPHANYBF_INSN_BL, EPIPHANYBF_INSN_JR16, EPIPHANYBF_INSN_JR
 , EPIPHANYBF_INSN_JALR16, EPIPHANYBF_INSN_JALR, EPIPHANYBF_INSN_LDRBX16_S, EPIPHANYBF_INSN_LDRBP16_S
 , EPIPHANYBF_INSN_LDRBX_L, EPIPHANYBF_INSN_LDRBP_L, EPIPHANYBF_INSN_LDRBD16_S, EPIPHANYBF_INSN_LDRBD_L
 , EPIPHANYBF_INSN_LDRBDPM_L, EPIPHANYBF_INSN_LDRHX16_S, EPIPHANYBF_INSN_LDRHP16_S, EPIPHANYBF_INSN_LDRHX_L
 , EPIPHANYBF_INSN_LDRHP_L, EPIPHANYBF_INSN_LDRHD16_S, EPIPHANYBF_INSN_LDRHD_L, EPIPHANYBF_INSN_LDRHDPM_L
 , EPIPHANYBF_INSN_LDRX16_S, EPIPHANYBF_INSN_LDRP16_S, EPIPHANYBF_INSN_LDRX_L, EPIPHANYBF_INSN_LDRP_L
 , EPIPHANYBF_INSN_LDRD16_S, EPIPHANYBF_INSN_LDRD_L, EPIPHANYBF_INSN_LDRDPM_L, EPIPHANYBF_INSN_LDRDX16_S
 , EPIPHANYBF_INSN_LDRDP16_S, EPIPHANYBF_INSN_LDRDX_L, EPIPHANYBF_INSN_LDRDP_L, EPIPHANYBF_INSN_LDRDD16_S
 , EPIPHANYBF_INSN_LDRDD_L, EPIPHANYBF_INSN_LDRDDPM_L, EPIPHANYBF_INSN_TESTSETBT, EPIPHANYBF_INSN_TESTSETHT
 , EPIPHANYBF_INSN_TESTSETT, EPIPHANYBF_INSN_STRBX16, EPIPHANYBF_INSN_STRBX, EPIPHANYBF_INSN_STRBP16
 , EPIPHANYBF_INSN_STRBP, EPIPHANYBF_INSN_STRBD16, EPIPHANYBF_INSN_STRBD, EPIPHANYBF_INSN_STRBDPM
 , EPIPHANYBF_INSN_STRHX16, EPIPHANYBF_INSN_STRHX, EPIPHANYBF_INSN_STRHP16, EPIPHANYBF_INSN_STRHP
 , EPIPHANYBF_INSN_STRHD16, EPIPHANYBF_INSN_STRHD, EPIPHANYBF_INSN_STRHDPM, EPIPHANYBF_INSN_STRX16
 , EPIPHANYBF_INSN_STRX, EPIPHANYBF_INSN_STRP16, EPIPHANYBF_INSN_STRP, EPIPHANYBF_INSN_STRD16
 , EPIPHANYBF_INSN_STRD, EPIPHANYBF_INSN_STRDPM, EPIPHANYBF_INSN_STRDX16, EPIPHANYBF_INSN_STRDX
 , EPIPHANYBF_INSN_STRDP16, EPIPHANYBF_INSN_STRDP, EPIPHANYBF_INSN_STRDD16, EPIPHANYBF_INSN_STRDD
 , EPIPHANYBF_INSN_STRDDPM, EPIPHANYBF_INSN_CMOV16EQ, EPIPHANYBF_INSN_CMOVEQ, EPIPHANYBF_INSN_CMOV16NE
 , EPIPHANYBF_INSN_CMOVNE, EPIPHANYBF_INSN_CMOV16GTU, EPIPHANYBF_INSN_CMOVGTU, EPIPHANYBF_INSN_CMOV16GTEU
 , EPIPHANYBF_INSN_CMOVGTEU, EPIPHANYBF_INSN_CMOV16LTEU, EPIPHANYBF_INSN_CMOVLTEU, EPIPHANYBF_INSN_CMOV16LTU
 , EPIPHANYBF_INSN_CMOVLTU, EPIPHANYBF_INSN_CMOV16GT, EPIPHANYBF_INSN_CMOVGT, EPIPHANYBF_INSN_CMOV16GTE
 , EPIPHANYBF_INSN_CMOVGTE, EPIPHANYBF_INSN_CMOV16LT, EPIPHANYBF_INSN_CMOVLT, EPIPHANYBF_INSN_CMOV16LTE
 , EPIPHANYBF_INSN_CMOVLTE, EPIPHANYBF_INSN_CMOV16B, EPIPHANYBF_INSN_CMOVB, EPIPHANYBF_INSN_CMOV16BEQ
 , EPIPHANYBF_INSN_CMOVBEQ, EPIPHANYBF_INSN_CMOV16BNE, EPIPHANYBF_INSN_CMOVBNE, EPIPHANYBF_INSN_CMOV16BLT
 , EPIPHANYBF_INSN_CMOVBLT, EPIPHANYBF_INSN_CMOV16BLTE, EPIPHANYBF_INSN_CMOVBLTE, EPIPHANYBF_INSN_MOVTS16
 , EPIPHANYBF_INSN_MOVTS6, EPIPHANYBF_INSN_MOVTSDMA, EPIPHANYBF_INSN_MOVTSMEM, EPIPHANYBF_INSN_MOVTSMESH
 , EPIPHANYBF_INSN_MOVFS16, EPIPHANYBF_INSN_MOVFS6, EPIPHANYBF_INSN_MOVFSDMA, EPIPHANYBF_INSN_MOVFSMEM
 , EPIPHANYBF_INSN_MOVFSMESH, EPIPHANYBF_INSN_NOP, EPIPHANYBF_INSN_SNOP, EPIPHANYBF_INSN_UNIMPL
 , EPIPHANYBF_INSN_IDLE, EPIPHANYBF_INSN_BKPT, EPIPHANYBF_INSN_MBKPT, EPIPHANYBF_INSN_RTI
 , EPIPHANYBF_INSN_WAND, EPIPHANYBF_INSN_SYNC, EPIPHANYBF_INSN_GIEN, EPIPHANYBF_INSN_GIDIS
 , EPIPHANYBF_INSN_SWI_NUM, EPIPHANYBF_INSN_TRAP16, EPIPHANYBF_INSN_ADD16, EPIPHANYBF_INSN_ADD
 , EPIPHANYBF_INSN_SUB16, EPIPHANYBF_INSN_SUB, EPIPHANYBF_INSN_AND16, EPIPHANYBF_INSN_AND
 , EPIPHANYBF_INSN_ORR16, EPIPHANYBF_INSN_ORR, EPIPHANYBF_INSN_EOR16, EPIPHANYBF_INSN_EOR
 , EPIPHANYBF_INSN_ADDI16, EPIPHANYBF_INSN_ADDI, EPIPHANYBF_INSN_SUBI16, EPIPHANYBF_INSN_SUBI
 , EPIPHANYBF_INSN_ASR16, EPIPHANYBF_INSN_ASR, EPIPHANYBF_INSN_LSR16, EPIPHANYBF_INSN_LSR
 , EPIPHANYBF_INSN_LSL16, EPIPHANYBF_INSN_LSL, EPIPHANYBF_INSN_LSRI16, EPIPHANYBF_INSN_LSRI32
 , EPIPHANYBF_INSN_LSLI16, EPIPHANYBF_INSN_LSLI32, EPIPHANYBF_INSN_ASRI16, EPIPHANYBF_INSN_ASRI32
 , EPIPHANYBF_INSN_BITR16, EPIPHANYBF_INSN_BITR, EPIPHANYBF_INSN_FEXT, EPIPHANYBF_INSN_FDEP
 , EPIPHANYBF_INSN_LFSR, EPIPHANYBF_INSN_MOV8, EPIPHANYBF_INSN_MOV16, EPIPHANYBF_INSN_MOVT
 , EPIPHANYBF_INSN_F_ADDF16, EPIPHANYBF_INSN_F_ADDF32, EPIPHANYBF_INSN_F_SUBF16, EPIPHANYBF_INSN_F_SUBF32
 , EPIPHANYBF_INSN_F_MULF16, EPIPHANYBF_INSN_F_MULF32, EPIPHANYBF_INSN_F_MADDF16, EPIPHANYBF_INSN_F_MADDF32
 , EPIPHANYBF_INSN_F_MSUBF16, EPIPHANYBF_INSN_F_MSUBF32, EPIPHANYBF_INSN_F_ABSF16, EPIPHANYBF_INSN_F_ABSF32
 , EPIPHANYBF_INSN_F_LOATF16, EPIPHANYBF_INSN_F_LOATF32, EPIPHANYBF_INSN_F_IXF16, EPIPHANYBF_INSN_F_IXF32
 , EPIPHANYBF_INSN_F_RECIPF32, EPIPHANYBF_INSN_F_SQRTF32, EPIPHANYBF_INSN__MAX
} EPIPHANYBF_INSN_TYPE;

/* Enum declaration for semantic formats in cpu family epiphanybf.  */
typedef enum epiphanybf_sfmt_type {
  EPIPHANYBF_SFMT_EMPTY, EPIPHANYBF_SFMT_BEQ16, EPIPHANYBF_SFMT_BEQ, EPIPHANYBF_SFMT_BGTU16
 , EPIPHANYBF_SFMT_BGTU, EPIPHANYBF_SFMT_BGTEU16, EPIPHANYBF_SFMT_BGTEU, EPIPHANYBF_SFMT_BGT16
 , EPIPHANYBF_SFMT_BGT, EPIPHANYBF_SFMT_BGTE16, EPIPHANYBF_SFMT_BGTE, EPIPHANYBF_SFMT_BBEQ16
 , EPIPHANYBF_SFMT_BBEQ, EPIPHANYBF_SFMT_BBLT16, EPIPHANYBF_SFMT_BBLT, EPIPHANYBF_SFMT_B16
 , EPIPHANYBF_SFMT_B, EPIPHANYBF_SFMT_BL16, EPIPHANYBF_SFMT_BL, EPIPHANYBF_SFMT_JR16
 , EPIPHANYBF_SFMT_JR, EPIPHANYBF_SFMT_JALR16, EPIPHANYBF_SFMT_JALR, EPIPHANYBF_SFMT_LDRBX16_S
 , EPIPHANYBF_SFMT_LDRBP16_S, EPIPHANYBF_SFMT_LDRBX_L, EPIPHANYBF_SFMT_LDRBP_L, EPIPHANYBF_SFMT_LDRBD16_S
 , EPIPHANYBF_SFMT_LDRBD_L, EPIPHANYBF_SFMT_LDRBDPM_L, EPIPHANYBF_SFMT_LDRHX16_S, EPIPHANYBF_SFMT_LDRHP16_S
 , EPIPHANYBF_SFMT_LDRHX_L, EPIPHANYBF_SFMT_LDRHP_L, EPIPHANYBF_SFMT_LDRHD16_S, EPIPHANYBF_SFMT_LDRHD_L
 , EPIPHANYBF_SFMT_LDRHDPM_L, EPIPHANYBF_SFMT_LDRX16_S, EPIPHANYBF_SFMT_LDRP16_S, EPIPHANYBF_SFMT_LDRX_L
 , EPIPHANYBF_SFMT_LDRP_L, EPIPHANYBF_SFMT_LDRD16_S, EPIPHANYBF_SFMT_LDRD_L, EPIPHANYBF_SFMT_LDRDPM_L
 , EPIPHANYBF_SFMT_LDRDX16_S, EPIPHANYBF_SFMT_LDRDP16_S, EPIPHANYBF_SFMT_LDRDX_L, EPIPHANYBF_SFMT_LDRDP_L
 , EPIPHANYBF_SFMT_LDRDD16_S, EPIPHANYBF_SFMT_LDRDD_L, EPIPHANYBF_SFMT_LDRDDPM_L, EPIPHANYBF_SFMT_TESTSETBT
 , EPIPHANYBF_SFMT_STRBX16, EPIPHANYBF_SFMT_STRBX, EPIPHANYBF_SFMT_STRBP16, EPIPHANYBF_SFMT_STRBP
 , EPIPHANYBF_SFMT_STRBD16, EPIPHANYBF_SFMT_STRBD, EPIPHANYBF_SFMT_STRBDPM, EPIPHANYBF_SFMT_STRHX16
 , EPIPHANYBF_SFMT_STRHX, EPIPHANYBF_SFMT_STRHP16, EPIPHANYBF_SFMT_STRHP, EPIPHANYBF_SFMT_STRHD16
 , EPIPHANYBF_SFMT_STRHD, EPIPHANYBF_SFMT_STRHDPM, EPIPHANYBF_SFMT_STRX16, EPIPHANYBF_SFMT_STRX
 , EPIPHANYBF_SFMT_STRP16, EPIPHANYBF_SFMT_STRP, EPIPHANYBF_SFMT_STRD16, EPIPHANYBF_SFMT_STRD
 , EPIPHANYBF_SFMT_STRDPM, EPIPHANYBF_SFMT_STRDX16, EPIPHANYBF_SFMT_STRDX, EPIPHANYBF_SFMT_STRDP16
 , EPIPHANYBF_SFMT_STRDP, EPIPHANYBF_SFMT_STRDD16, EPIPHANYBF_SFMT_STRDD, EPIPHANYBF_SFMT_STRDDPM
 , EPIPHANYBF_SFMT_CMOV16EQ, EPIPHANYBF_SFMT_CMOVEQ, EPIPHANYBF_SFMT_CMOV16GTU, EPIPHANYBF_SFMT_CMOVGTU
 , EPIPHANYBF_SFMT_CMOV16GTEU, EPIPHANYBF_SFMT_CMOVGTEU, EPIPHANYBF_SFMT_CMOV16GT, EPIPHANYBF_SFMT_CMOVGT
 , EPIPHANYBF_SFMT_CMOV16GTE, EPIPHANYBF_SFMT_CMOVGTE, EPIPHANYBF_SFMT_CMOV16B, EPIPHANYBF_SFMT_CMOVB
 , EPIPHANYBF_SFMT_CMOV16BEQ, EPIPHANYBF_SFMT_CMOVBEQ, EPIPHANYBF_SFMT_CMOV16BLT, EPIPHANYBF_SFMT_CMOVBLT
 , EPIPHANYBF_SFMT_MOVTS16, EPIPHANYBF_SFMT_MOVTS6, EPIPHANYBF_SFMT_MOVTSDMA, EPIPHANYBF_SFMT_MOVTSMEM
 , EPIPHANYBF_SFMT_MOVTSMESH, EPIPHANYBF_SFMT_MOVFS16, EPIPHANYBF_SFMT_MOVFS6, EPIPHANYBF_SFMT_MOVFSDMA
 , EPIPHANYBF_SFMT_MOVFSMEM, EPIPHANYBF_SFMT_MOVFSMESH, EPIPHANYBF_SFMT_NOP, EPIPHANYBF_SFMT_IDLE
 , EPIPHANYBF_SFMT_BKPT, EPIPHANYBF_SFMT_MBKPT, EPIPHANYBF_SFMT_RTI, EPIPHANYBF_SFMT_WAND
 , EPIPHANYBF_SFMT_GIDIS, EPIPHANYBF_SFMT_SWI_NUM, EPIPHANYBF_SFMT_TRAP16, EPIPHANYBF_SFMT_ADD16
 , EPIPHANYBF_SFMT_ADD, EPIPHANYBF_SFMT_AND16, EPIPHANYBF_SFMT_AND, EPIPHANYBF_SFMT_ADDI16
 , EPIPHANYBF_SFMT_ADDI, EPIPHANYBF_SFMT_LSRI16, EPIPHANYBF_SFMT_LSRI32, EPIPHANYBF_SFMT_BITR16
 , EPIPHANYBF_SFMT_BITR, EPIPHANYBF_SFMT_FEXT, EPIPHANYBF_SFMT_MOV8, EPIPHANYBF_SFMT_MOV16
 , EPIPHANYBF_SFMT_MOVT, EPIPHANYBF_SFMT_F_ADDF16, EPIPHANYBF_SFMT_F_ADDF32, EPIPHANYBF_SFMT_F_ABSF16
 , EPIPHANYBF_SFMT_F_ABSF32, EPIPHANYBF_SFMT_F_LOATF16, EPIPHANYBF_SFMT_F_IXF16, EPIPHANYBF_SFMT_F_IXF32
 , EPIPHANYBF_SFMT_F_RECIPF32
} EPIPHANYBF_SFMT_TYPE;

/* Function unit handlers (user written).  */

extern int epiphanybf_model_epiphany32_u_exec (SIM_CPU *, const IDESC *, int /*unit_num*/, int /*referenced*/);

/* Profiling before/after handlers (user written) */

extern void epiphanybf_model_insn_before (SIM_CPU *, int /*first_p*/);
extern void epiphanybf_model_insn_after (SIM_CPU *, int /*last_p*/, int /*cycles*/);

#endif /* EPIPHANYBF_DECODE_H */
